export enum ConversationStateType {
	CHATTING_WITH_EMPLOYEE = 'CHATTING_WITH_EMPLOYEE',
	CHATTING_WITH_CLIENT = 'CHATTING_WITH_CLIENT',
	CHATTING_WITH_AI = 'CHATTING_WITH_AI',
	DEPARTMENT_QUEUE = 'DEPARTMENT_QUEUE',
	SELECTING_DEPARTMENT = 'SELECTING_DEPARTMENT',
	LISTING_DEPARTMENT_QUEUE = 'LISTING_DEPARTMENT_QUEUE',
	SELECTING_FAQ_CATEGORY = 'SELECTING_FAQ_CATEGORY',
	LISTING_FAQ_ITEMS = 'LISTING_FAQ_ITEMS',
	INITIAL_MENU = 'INITIAL_MENU',
	BEGIN = 'BEGIN',
}
